version: '3.7'

services:
  postgres:
    container_name: acnw-postgres
    image: postgres:10-alpine
    restart: unless-stopped
    ports:
      - "54320:5432"
    stop_signal: SIGINT
    environment:
      - POSTGRES_USER=ggp
      - POSTGRES_PASSWORD=
    command: -c log_statement=all -c log_min_error_statement=error
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mysql:
    container_name: acnw-mysql
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "33060:3306"
    stop_signal: SIGINT
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword

volumes:
  postgres-data:
